import 'dart:ui';

import 'package:equatable/equatable.dart';
import 'package:whiteboard/domain/entities/anchor_point.dart';

sealed class ConnectorNode extends Equatable {
  const ConnectorNode({required this.position});

  final Offset position;

  @override
  List<Object?> get props => [position];
}

class AnchorNode extends ConnectorNode {
  const AnchorNode({required this.anchor, required super.position});

  final AnchorPoint anchor;

  @override
  List<Object?> get props => [anchor, ...super.props];
}

class WaypointNode extends ConnectorNode {
  const WaypointNode({required super.position});
}

/// A midpoint node that appears on segments adjacent to anchors.
///
/// This node allows users to grab and drag to create new waypoints.
/// When dragged, it converts to a [WaypointNode] and new [SegmentMidNode]s
/// are created on the resulting segments.
///
/// Unlike [WaypointNode], these are auto-generated by the router and
/// are not persisted - they're purely for interaction.
class SegmentMidNode extends ConnectorNode {
  const SegmentMidNode({required super.position});
}
